// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Block struct {
	Blockindex           uint32         `protobuf:"varint,1,opt,name=blockindex,proto3" json:"blockindex,omitempty"`
	Version              []byte         `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Header               *BlockHeader   `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	Size                 uint32         `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Reward               float32        `protobuf:"fixed32,5,opt,name=reward,proto3" json:"reward,omitempty"`
	Txvalues             float32        `protobuf:"fixed32,6,opt,name=txvalues,proto3" json:"txvalues,omitempty"`
	Txcount              uint32         `protobuf:"varint,7,opt,name=txcount,proto3" json:"txcount,omitempty"`
	Merkleroot           []byte         `protobuf:"bytes,8,opt,name=merkleroot,proto3" json:"merkleroot,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,9,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Timestamp            int64          `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d91b2d037e7a44, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetBlockindex() uint32 {
	if m != nil {
		return m.Blockindex
	}
	return 0
}

func (m *Block) GetVersion() []byte {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Block) GetReward() float32 {
	if m != nil {
		return m.Reward
	}
	return 0
}

func (m *Block) GetTxvalues() float32 {
	if m != nil {
		return m.Txvalues
	}
	return 0
}

func (m *Block) GetTxcount() uint32 {
	if m != nil {
		return m.Txcount
	}
	return 0
}

func (m *Block) GetMerkleroot() []byte {
	if m != nil {
		return m.Merkleroot
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type BlockHeader struct {
	Chainid              uint32   `protobuf:"varint,1,opt,name=chainid,proto3" json:"chainid,omitempty"`
	Height               uint32   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Difficulty           uint32   `protobuf:"varint,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Nonce                []byte   `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Hash                 []byte   `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature            []byte   `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp            int64    `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Blocktype            []byte   `protobuf:"bytes,8,opt,name=blocktype,proto3" json:"blocktype,omitempty"`
	Blockversion         []byte   `protobuf:"bytes,9,opt,name=blockversion,proto3" json:"blockversion,omitempty"`
	Blocknetwork         []byte   `protobuf:"bytes,10,opt,name=blocknetwork,proto3" json:"blocknetwork,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d91b2d037e7a44, []int{1}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetChainid() uint32 {
	if m != nil {
		return m.Chainid
	}
	return 0
}

func (m *BlockHeader) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockHeader) GetDifficulty() uint32 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

func (m *BlockHeader) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHeader) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *BlockHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeader) GetBlocktype() []byte {
	if m != nil {
		return m.Blocktype
	}
	return nil
}

func (m *BlockHeader) GetBlockversion() []byte {
	if m != nil {
		return m.Blockversion
	}
	return nil
}

func (m *BlockHeader) GetBlocknetwork() []byte {
	if m != nil {
		return m.Blocknetwork
	}
	return nil
}

type Transaction struct {
	Id                   []byte                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Inputs               []*Transaction_Input    `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*Transaction_Output   `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Utxo                 *Transaction_SignedUTXO `protobuf:"bytes,4,opt,name=utxo,proto3" json:"utxo,omitempty"`
	Timestamp            int64                   `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d91b2d037e7a44, []int{2}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Transaction) GetInputs() []*Transaction_Input {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Transaction) GetOutputs() []*Transaction_Output {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *Transaction) GetUtxo() *Transaction_SignedUTXO {
	if m != nil {
		return m.Utxo
	}
	return nil
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Transaction_Output struct {
	Amount               float32  `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_Output) Reset()         { *m = Transaction_Output{} }
func (m *Transaction_Output) String() string { return proto.CompactTextString(m) }
func (*Transaction_Output) ProtoMessage()    {}
func (*Transaction_Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d91b2d037e7a44, []int{2, 0}
}

func (m *Transaction_Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_Output.Unmarshal(m, b)
}
func (m *Transaction_Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_Output.Marshal(b, m, deterministic)
}
func (m *Transaction_Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_Output.Merge(m, src)
}
func (m *Transaction_Output) XXX_Size() int {
	return xxx_messageInfo_Transaction_Output.Size(m)
}
func (m *Transaction_Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_Output proto.InternalMessageInfo

func (m *Transaction_Output) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction_Output) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Transaction_Output) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Transaction_Input struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Nonce                []byte   `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Index                string   `protobuf:"bytes,4,opt,name=index,proto3" json:"index,omitempty"`
	Txtype               string   `protobuf:"bytes,5,opt,name=txtype,proto3" json:"txtype,omitempty"`
	Amount               float32  `protobuf:"fixed32,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Address              string   `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Signature            []byte   `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_Input) Reset()         { *m = Transaction_Input{} }
func (m *Transaction_Input) String() string { return proto.CompactTextString(m) }
func (*Transaction_Input) ProtoMessage()    {}
func (*Transaction_Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d91b2d037e7a44, []int{2, 1}
}

func (m *Transaction_Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_Input.Unmarshal(m, b)
}
func (m *Transaction_Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_Input.Marshal(b, m, deterministic)
}
func (m *Transaction_Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_Input.Merge(m, src)
}
func (m *Transaction_Input) XXX_Size() int {
	return xxx_messageInfo_Transaction_Input.Size(m)
}
func (m *Transaction_Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_Input proto.InternalMessageInfo

func (m *Transaction_Input) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *Transaction_Input) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction_Input) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Transaction_Input) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Transaction_Input) GetTxtype() string {
	if m != nil {
		return m.Txtype
	}
	return ""
}

func (m *Transaction_Input) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction_Input) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Transaction_Input) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Transaction_SignedUTXO struct {
	Outpoint             []byte   `protobuf:"bytes,1,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_SignedUTXO) Reset()         { *m = Transaction_SignedUTXO{} }
func (m *Transaction_SignedUTXO) String() string { return proto.CompactTextString(m) }
func (*Transaction_SignedUTXO) ProtoMessage()    {}
func (*Transaction_SignedUTXO) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d91b2d037e7a44, []int{2, 2}
}

func (m *Transaction_SignedUTXO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_SignedUTXO.Unmarshal(m, b)
}
func (m *Transaction_SignedUTXO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_SignedUTXO.Marshal(b, m, deterministic)
}
func (m *Transaction_SignedUTXO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_SignedUTXO.Merge(m, src)
}
func (m *Transaction_SignedUTXO) XXX_Size() int {
	return xxx_messageInfo_Transaction_SignedUTXO.Size(m)
}
func (m *Transaction_SignedUTXO) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_SignedUTXO.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_SignedUTXO proto.InternalMessageInfo

func (m *Transaction_SignedUTXO) GetOutpoint() []byte {
	if m != nil {
		return m.Outpoint
	}
	return nil
}

func (m *Transaction_SignedUTXO) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Transaction_SignedTX struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_SignedTX) Reset()         { *m = Transaction_SignedTX{} }
func (m *Transaction_SignedTX) String() string { return proto.CompactTextString(m) }
func (*Transaction_SignedTX) ProtoMessage()    {}
func (*Transaction_SignedTX) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d91b2d037e7a44, []int{2, 3}
}

func (m *Transaction_SignedTX) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_SignedTX.Unmarshal(m, b)
}
func (m *Transaction_SignedTX) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_SignedTX.Marshal(b, m, deterministic)
}
func (m *Transaction_SignedTX) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_SignedTX.Merge(m, src)
}
func (m *Transaction_SignedTX) XXX_Size() int {
	return xxx_messageInfo_Transaction_SignedTX.Size(m)
}
func (m *Transaction_SignedTX) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_SignedTX.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_SignedTX proto.InternalMessageInfo

func (m *Transaction_SignedTX) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *Transaction_SignedTX) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type SignedLimitOrder struct {
	SerializedLimitOrder []byte   `protobuf:"bytes,1,opt,name=serializedLimitOrder,proto3" json:"serializedLimitOrder,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedLimitOrder) Reset()         { *m = SignedLimitOrder{} }
func (m *SignedLimitOrder) String() string { return proto.CompactTextString(m) }
func (*SignedLimitOrder) ProtoMessage()    {}
func (*SignedLimitOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d91b2d037e7a44, []int{3}
}

func (m *SignedLimitOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedLimitOrder.Unmarshal(m, b)
}
func (m *SignedLimitOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedLimitOrder.Marshal(b, m, deterministic)
}
func (m *SignedLimitOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedLimitOrder.Merge(m, src)
}
func (m *SignedLimitOrder) XXX_Size() int {
	return xxx_messageInfo_SignedLimitOrder.Size(m)
}
func (m *SignedLimitOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedLimitOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SignedLimitOrder proto.InternalMessageInfo

func (m *SignedLimitOrder) GetSerializedLimitOrder() []byte {
	if m != nil {
		return m.SerializedLimitOrder
	}
	return nil
}

func (m *SignedLimitOrder) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type LimitOrder struct {
	PeerID               string                 `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	BuyBTC               bool                   `protobuf:"varint,2,opt,name=buyBTC,proto3" json:"buyBTC,omitempty"`
	BuySwagg             bool                   `protobuf:"varint,3,opt,name=buySwagg,proto3" json:"buySwagg,omitempty"`
	BuyDoge              bool                   `protobuf:"varint,4,opt,name=buyDoge,proto3" json:"buyDoge,omitempty"`
	Quantity             uint64                 `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                uint64                 `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Utxo                 *LimitOrder_SignedUTXO `protobuf:"bytes,7,opt,name=utxo,proto3" json:"utxo,omitempty"`
	Expiry               int64                  `protobuf:"varint,8,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LimitOrder) Reset()         { *m = LimitOrder{} }
func (m *LimitOrder) String() string { return proto.CompactTextString(m) }
func (*LimitOrder) ProtoMessage()    {}
func (*LimitOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d91b2d037e7a44, []int{4}
}

func (m *LimitOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LimitOrder.Unmarshal(m, b)
}
func (m *LimitOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LimitOrder.Marshal(b, m, deterministic)
}
func (m *LimitOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LimitOrder.Merge(m, src)
}
func (m *LimitOrder) XXX_Size() int {
	return xxx_messageInfo_LimitOrder.Size(m)
}
func (m *LimitOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_LimitOrder.DiscardUnknown(m)
}

var xxx_messageInfo_LimitOrder proto.InternalMessageInfo

func (m *LimitOrder) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

func (m *LimitOrder) GetBuyBTC() bool {
	if m != nil {
		return m.BuyBTC
	}
	return false
}

func (m *LimitOrder) GetBuySwagg() bool {
	if m != nil {
		return m.BuySwagg
	}
	return false
}

func (m *LimitOrder) GetBuyDoge() bool {
	if m != nil {
		return m.BuyDoge
	}
	return false
}

func (m *LimitOrder) GetQuantity() uint64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *LimitOrder) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *LimitOrder) GetUtxo() *LimitOrder_SignedUTXO {
	if m != nil {
		return m.Utxo
	}
	return nil
}

func (m *LimitOrder) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type LimitOrder_SignedUTXO struct {
	Outpoint             []byte   `protobuf:"bytes,1,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LimitOrder_SignedUTXO) Reset()         { *m = LimitOrder_SignedUTXO{} }
func (m *LimitOrder_SignedUTXO) String() string { return proto.CompactTextString(m) }
func (*LimitOrder_SignedUTXO) ProtoMessage()    {}
func (*LimitOrder_SignedUTXO) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d91b2d037e7a44, []int{4, 0}
}

func (m *LimitOrder_SignedUTXO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LimitOrder_SignedUTXO.Unmarshal(m, b)
}
func (m *LimitOrder_SignedUTXO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LimitOrder_SignedUTXO.Marshal(b, m, deterministic)
}
func (m *LimitOrder_SignedUTXO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LimitOrder_SignedUTXO.Merge(m, src)
}
func (m *LimitOrder_SignedUTXO) XXX_Size() int {
	return xxx_messageInfo_LimitOrder_SignedUTXO.Size(m)
}
func (m *LimitOrder_SignedUTXO) XXX_DiscardUnknown() {
	xxx_messageInfo_LimitOrder_SignedUTXO.DiscardUnknown(m)
}

var xxx_messageInfo_LimitOrder_SignedUTXO proto.InternalMessageInfo

func (m *LimitOrder_SignedUTXO) GetOutpoint() []byte {
	if m != nil {
		return m.Outpoint
	}
	return nil
}

func (m *LimitOrder_SignedUTXO) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type SignedRemoveOrder struct {
	OrderID              string   `protobuf:"bytes,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedRemoveOrder) Reset()         { *m = SignedRemoveOrder{} }
func (m *SignedRemoveOrder) String() string { return proto.CompactTextString(m) }
func (*SignedRemoveOrder) ProtoMessage()    {}
func (*SignedRemoveOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d91b2d037e7a44, []int{5}
}

func (m *SignedRemoveOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedRemoveOrder.Unmarshal(m, b)
}
func (m *SignedRemoveOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedRemoveOrder.Marshal(b, m, deterministic)
}
func (m *SignedRemoveOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedRemoveOrder.Merge(m, src)
}
func (m *SignedRemoveOrder) XXX_Size() int {
	return xxx_messageInfo_SignedRemoveOrder.Size(m)
}
func (m *SignedRemoveOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedRemoveOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SignedRemoveOrder proto.InternalMessageInfo

func (m *SignedRemoveOrder) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *SignedRemoveOrder) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*Block)(nil), "Block")
	proto.RegisterType((*BlockHeader)(nil), "BlockHeader")
	proto.RegisterType((*Transaction)(nil), "Transaction")
	proto.RegisterType((*Transaction_Output)(nil), "Transaction.Output")
	proto.RegisterType((*Transaction_Input)(nil), "Transaction.Input")
	proto.RegisterType((*Transaction_SignedUTXO)(nil), "Transaction.SignedUTXO")
	proto.RegisterType((*Transaction_SignedTX)(nil), "Transaction.SignedTX")
	proto.RegisterType((*SignedLimitOrder)(nil), "SignedLimitOrder")
	proto.RegisterType((*LimitOrder)(nil), "LimitOrder")
	proto.RegisterType((*LimitOrder_SignedUTXO)(nil), "LimitOrder.SignedUTXO")
	proto.RegisterType((*SignedRemoveOrder)(nil), "SignedRemoveOrder")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_d4d91b2d037e7a44) }

var fileDescriptor_d4d91b2d037e7a44 = []byte{
	// 741 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0x95, 0x1d, 0xc7, 0x49, 0x26, 0xee, 0xa7, 0x8f, 0xa5, 0x0a, 0x56, 0x84, 0x50, 0x14, 0x71,
	0x88, 0x8a, 0x88, 0x50, 0xb9, 0x72, 0x2a, 0x15, 0xa2, 0x02, 0x51, 0x69, 0x1b, 0xa4, 0x8a, 0xdb,
	0x26, 0xde, 0x26, 0xab, 0x26, 0x5e, 0xb3, 0x5e, 0xb7, 0x71, 0xff, 0x12, 0x17, 0xae, 0x9c, 0xf9,
	0x21, 0xfc, 0x15, 0xb4, 0xe3, 0xb5, 0x63, 0x87, 0x02, 0x17, 0x6e, 0xfb, 0xde, 0x8c, 0x27, 0x6f,
	0xdf, 0x9b, 0x55, 0xa0, 0xbf, 0x58, 0x31, 0x11, 0x4f, 0x13, 0x25, 0xb5, 0x1c, 0x7f, 0x73, 0xa1,
	0x7d, 0xb2, 0x96, 0x8b, 0x6b, 0xf2, 0x04, 0x60, 0x6e, 0x0e, 0x22, 0x8e, 0xf8, 0x36, 0x74, 0x46,
	0xce, 0xe4, 0x80, 0xd6, 0x18, 0x12, 0x42, 0xe7, 0x86, 0xab, 0x54, 0xc8, 0x38, 0x74, 0x47, 0xce,
	0x24, 0xa0, 0x25, 0x24, 0x4f, 0xc1, 0x5f, 0x71, 0x16, 0x71, 0x15, 0xb6, 0x46, 0xce, 0xa4, 0x7f,
	0x1c, 0x4c, 0x71, 0xe2, 0x5b, 0xe4, 0xa8, 0xad, 0x11, 0x02, 0x5e, 0x2a, 0xee, 0x78, 0xe8, 0xe1,
	0x64, 0x3c, 0x93, 0x01, 0xf8, 0x8a, 0xdf, 0x32, 0x15, 0x85, 0xed, 0x91, 0x33, 0x71, 0xa9, 0x45,
	0x64, 0x08, 0x5d, 0xbd, 0xbd, 0x61, 0xeb, 0x8c, 0xa7, 0xa1, 0x8f, 0x95, 0x0a, 0x1b, 0x1d, 0x7a,
	0xbb, 0x90, 0x59, 0xac, 0xc3, 0x0e, 0x8e, 0x2a, 0xa1, 0xb9, 0xc1, 0x86, 0xab, 0xeb, 0x35, 0x57,
	0x52, 0xea, 0xb0, 0x8b, 0x22, 0x6b, 0x0c, 0x79, 0x01, 0x81, 0x56, 0x2c, 0x4e, 0xd9, 0x42, 0x0b,
	0x19, 0xa7, 0x61, 0x6f, 0xd4, 0x42, 0xb5, 0xb3, 0x1d, 0x49, 0x1b, 0x1d, 0xe4, 0x31, 0xf4, 0xb4,
	0xd8, 0xf0, 0x54, 0xb3, 0x4d, 0x12, 0xc2, 0xc8, 0x99, 0xb4, 0xe8, 0x8e, 0x18, 0x7f, 0x71, 0xa1,
	0x5f, 0xbb, 0xa9, 0x51, 0x86, 0xd6, 0x8a, 0xc8, 0xda, 0x57, 0x42, 0x73, 0xcf, 0x15, 0x17, 0xcb,
	0x95, 0x46, 0xeb, 0x0e, 0xa8, 0x45, 0x46, 0x71, 0x24, 0xae, 0xae, 0xc4, 0x22, 0x5b, 0xeb, 0x1c,
	0xdd, 0x3b, 0xa0, 0x35, 0x86, 0x1c, 0x42, 0x3b, 0x96, 0xf1, 0xa2, 0x30, 0x2d, 0xa0, 0x05, 0x30,
	0x4e, 0xae, 0x58, 0xba, 0x42, 0xcf, 0x02, 0x8a, 0x67, 0xa3, 0x34, 0x15, 0xcb, 0x98, 0xe9, 0x4c,
	0x71, 0xb4, 0x2c, 0xa0, 0x3b, 0xa2, 0x79, 0x8f, 0xce, 0xde, 0x3d, 0x4c, 0x15, 0x73, 0xd6, 0x79,
	0xc2, 0xad, 0x6d, 0x3b, 0x82, 0x8c, 0x21, 0x40, 0x50, 0x86, 0xdf, 0xc3, 0x86, 0x06, 0x57, 0xf5,
	0xc4, 0x5c, 0xdf, 0x4a, 0x75, 0x8d, 0x56, 0x95, 0x3d, 0x96, 0x1b, 0xff, 0xf0, 0xa0, 0x5f, 0x73,
	0x9a, 0xfc, 0x07, 0xae, 0x35, 0x2a, 0xa0, 0xae, 0x88, 0xc8, 0x11, 0xf8, 0x22, 0x4e, 0x32, 0x9d,
	0x86, 0x2e, 0xe6, 0x42, 0xea, 0xb9, 0x4c, 0xcf, 0x4c, 0x89, 0xda, 0x0e, 0xf2, 0x1c, 0x3a, 0x32,
	0xd3, 0xd8, 0xdc, 0xc2, 0xe6, 0x87, 0x8d, 0xe6, 0x73, 0xac, 0xd1, 0xb2, 0x87, 0x3c, 0x03, 0x2f,
	0xd3, 0x5b, 0x89, 0x2e, 0xf6, 0x8f, 0x1f, 0x35, 0x7a, 0x2f, 0xc4, 0x32, 0xe6, 0xd1, 0xc7, 0xd9,
	0xe5, 0x39, 0xc5, 0xa6, 0xa6, 0x57, 0xed, 0x3d, 0xaf, 0x86, 0x1f, 0xc0, 0x2f, 0xa6, 0x9b, 0x4c,
	0xd9, 0x06, 0xd7, 0xd0, 0x29, 0x76, 0xb7, 0x40, 0x66, 0x0b, 0x58, 0x14, 0x29, 0x9e, 0xa6, 0x18,
	0x76, 0x8f, 0x96, 0xd0, 0xe4, 0x16, 0x31, 0xcd, 0x30, 0xe7, 0x80, 0xe2, 0x79, 0xf8, 0xdd, 0x81,
	0x36, 0xde, 0xcd, 0x54, 0xf5, 0xd6, 0x3a, 0xd2, 0xa3, 0x78, 0xae, 0x92, 0x76, 0x6b, 0x49, 0x57,
	0x3b, 0xd1, 0xaa, 0xef, 0xc4, 0x21, 0xb4, 0x8b, 0x87, 0xeb, 0xe1, 0xe7, 0x05, 0x30, 0x1a, 0xf5,
	0x16, 0x63, 0x6d, 0x23, 0x6d, 0x51, 0x4d, 0xbb, 0xff, 0x3b, 0xed, 0x9d, 0xa6, 0xf6, 0xc6, 0x7e,
	0x75, 0xf7, 0xf6, 0x6b, 0xf8, 0x06, 0x60, 0xe7, 0xa3, 0x79, 0xbd, 0xc6, 0x79, 0x29, 0xac, 0x37,
	0x01, 0xad, 0x70, 0x73, 0x8e, 0xbb, 0x3f, 0xe7, 0x15, 0x74, 0x8b, 0x39, 0xb3, 0xcb, 0x7b, 0xfd,
	0xf8, 0xe3, 0xd7, 0xe3, 0x08, 0xfe, 0x2f, 0xbe, 0x7e, 0x2f, 0x36, 0x42, 0x9f, 0x2b, 0xf3, 0x26,
	0x8f, 0xe1, 0x30, 0xe5, 0x4a, 0xb0, 0xb5, 0xb8, 0xab, 0xf3, 0x56, 0xd7, 0xbd, 0xb5, 0xbf, 0xfc,
	0xca, 0x57, 0x17, 0xa0, 0xd6, 0x3c, 0x00, 0x3f, 0xe1, 0x5c, 0x9d, 0x9d, 0x5a, 0xa1, 0x16, 0x19,
	0x7e, 0x9e, 0xe5, 0x27, 0xb3, 0xd7, 0x38, 0xa1, 0x4b, 0x2d, 0x32, 0xe6, 0xcc, 0xb3, 0xfc, 0xe2,
	0x96, 0x2d, 0x97, 0x98, 0x60, 0x97, 0x56, 0xd8, 0xd8, 0x3f, 0xcf, 0xf2, 0x53, 0xb9, 0x2c, 0x1e,
	0x7c, 0x97, 0x96, 0xd0, 0x7c, 0xf5, 0x39, 0x63, 0xb1, 0x16, 0x3a, 0xc7, 0x28, 0x3d, 0x5a, 0x61,
	0x13, 0x7d, 0xa2, 0xc4, 0xa2, 0x78, 0xf6, 0x1e, 0x2d, 0x00, 0x39, 0xb2, 0x3b, 0xdf, 0xc1, 0x9d,
	0x1f, 0x4c, 0x77, 0x92, 0x7f, 0x5d, 0xf9, 0x01, 0xf8, 0x7c, 0x9b, 0x08, 0x95, 0x63, 0xb2, 0x2d,
	0x6a, 0xd1, 0xbf, 0x8a, 0x75, 0xfc, 0x0e, 0x1e, 0x14, 0x73, 0x28, 0xdf, 0xc8, 0x1b, 0x5e, 0x18,
	0x17, 0x42, 0x07, 0x0f, 0x95, 0x73, 0x25, 0x6c, 0x0e, 0x6b, 0xed, 0x0d, 0x3b, 0xf1, 0x3e, 0xb9,
	0xc9, 0x7c, 0xee, 0xe3, 0xdf, 0xd7, 0xcb, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xa0, 0x93,
	0x7e, 0xcd, 0x06, 0x00, 0x00,
}
